services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
