# Generated by Django 5.0.6 on 2024-07-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='email',
        ),
    ]
