# Generated by Django 5.0.6 on 2024-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0002_remove_facultyprofile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'verbose_name': 'Faculty Profile', 'verbose_name_plural': 'Faculty Profiles'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dept',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EEE', 'Electrical and Electronics Engineering'), ('SFE', 'Safety Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='CS', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='dept',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EEE', 'Electrical and Electronics Engineering'), ('SFE', 'Safety Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='CS', max_length=100),
        ),
    ]
