# Generated by Django 5.0.6 on 2024-07-05 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0003_alter_facultyprofile_options_and_more'),
        ('project', '0002_alter_project_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
